language: c

dist: bionic

compiler:
  - gcc

# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:sri-csl/formal-methods
  - sudo apt-get -y update
  - sudo apt-get -y install yices2
  - sudo apt-get -y install java-common curl

install:
  -  curl https://d3pxv6yz143wms.cloudfront.net/8.222.10.1/java-1.8.0-amazon-corretto-jdk_8.222.10-1_amd64.deb	> java-1.8.0-amazon-corretto-jdk_8.222.10-1_amd64.deb
  - sudo dpkg --install java-1.8.0-amazon-corretto-jdk_8.222.10-1_amd64.deb
  - curl https://downloads.apache.org//ant/binaries/apache-ant-1.10.7-bin.tar.gz > apache-ant-1.10.7-bin.tar.gz
  - tar xvfz apache-ant-1.10.7-bin.tar.gz
  - sudo apt-get install ant


script:
  - ant -version
  - ant test
